server {
    listen 80;
    server_name _;

    location / {
        default_type application/json;
        return 200 '{"status":"ok","tier":"web"}';
    }

    location /health {
        default_type application/json;
        return 200 '{"status":"ok","tier":"web"}';
    }
}
